apiVersion: v1alpha
kind: puppeteer
sauce:
  region: us-west-1
  concurrency: 2
  metadata:
    name: Testing Puppeteer Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
rootDir: ./
puppeteer:
  version: 3.0.4
suites:
  - name: "chrome"
    testMatch: ["**/*.test.js"]
    browser: "chrome"
