name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  saucectl-docker-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          cache-from: saucelabs/stt-puppeteer-jest-node:latest
          push: false
          load: true
          tags: saucelabs/stt-puppeteer-jest-node:local
          build-args: |
            BUILD_TAG=${{ github.ref }}

      - name: Setup saucectl
        uses: saucelabs/saucectl-run-action@v2
        with:
          skip-run: true

      - name: Test
        working-directory: tests/e2e/
        run: saucectl run
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
