name: Docker Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: saucelabs/stt-puppeteer-jest-node
          tag_with_ref: true
          cache_froms: saucelabs/stt-puppeteer-jest-node:latest
          push: false
          tags: local

      - uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          saucectl-version: v0.34.0

      - name: Run tests
        working-directory: tests/e2e/
        run: saucectl run --test-env docker
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
